$(eval $(call start_directory,lib))
$(eval $(call std_header))
$(eval $(call add_to_lib_include_path))

SUBDIRS := libc libc++ libm libbdl libzlib libpng
$(eval $(call include_subdirs))


$(eval $(call std_footer))
