$(eval $(call start_directory,os))
$(eval $(call std_header))
$(eval $(call add_to_include_path))

os_OBJS = \
		  main.o \
	  	  babyos.o \
		  bootinfo.o \

KOBJS += $(call mkobjs,$(os_OBJS))

$(eval $(call std_footer))
